apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
namespace: team1

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kafka-properties
    files:
      - ./../config/kafka.properties
