{
 "title": "HTTP Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Connection lifespan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "armeria_server_connections_lifespan_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "armeria_server_connections" }
   ]
  },
  {
   "title": "Server Pending Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "armeria_server_pending_responses"
    }
   ]
  },
  { "title": "Kafka HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(kafkahttp_requests_total[5m])",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Total duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "kafkahttp_total_duration_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafkahttp_request_duration_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Response duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafkahttp_response_duration_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Response Lenght",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "kafkahttp_request_length", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Response Lenght",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "kafkahttp_response_length", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(kafkahttp_timeouts_total[5m])",
     "legendFormat": "{{cause}} - {{http_status}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "kafkahttp_active_requests" }
   ]
  }
 ]
}