{
 "title": "Kafka Streams",
 "time": { "from": "2022-02-16T15:52:12.362Z", "to": "2022-02-16T15:53:08.480Z" },
 "panels": [
  {
   "title": "Topics throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(ccloud_metric_received_records{topic=\"jeqo-test-v1\"}[5m])",
     "legendFormat": "input topic: {{topic}}"
    },
    {
     "expr": "rate(ccloud_metric_received_records{topic=\"jeqo-test-v1\"}[5m])",
     "legendFormat": "output topic: {{topic}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Poll Records by Thread",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kafka_stream_thread_poll_records_avg{}",
     "legendFormat": "{{thread_id}} (avg)"
    }
   ]
  },
  {
   "title": "Poll Records by Thread",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kafka_stream_thread_poll_records_max{}",
     "legendFormat": "{{thread_id}} (max)"
    }
   ]
  },
  {
   "title": "Poll rate by Thread ID",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "kafka_stream_thread_poll_rate", "legendFormat": "{{thread_id}}" },
    {
     "expr": "sum(kafka_stream_thread_poll_rate{})"
    }
   ]
  },
  {
   "title": "Process rate by Thread ID",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "kafka_stream_thread_process_rate{}",
     "legendFormat": "{{thread_id}}"
    },
    {
     "expr": "sum(kafka_stream_thread_process_rate{})"
    }
   ]
  },
  {
   "title": "Avg. Consumer Lag by Thread ID",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_avg{}",
     "legendFormat": "{{topic}}:{{partition}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Max Consumer Lag by Thread ID",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_max{}",
     "legendFormat": "{{topic}}:{{partition}} - {{client_id}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Poll Latency by Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_poll_latency_avg{}",
     "legendFormat": "{{ thread_id }} (avg)"
    }
   ]
  },
  {
   "title": "Poll Latency by Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_poll_latency_max",
     "legendFormat": "{{ thread_id }} (max)"
    }
   ]
  },
  {
   "title": "Process Latency by Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_process_latency_avg{}",
     "legendFormat": "{{thread_id}} (avg)"
    }
   ]
  },
  {
   "title": "Process Latency by Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_process_latency_max{}",
     "legendFormat": "{{thread_id}} (max)"
    }
   ]
  }
 ]
}