CREATE STREAM S1 (
  NAME STRING KEY,
  AGE BIGINT
)
WITH (
  KAFKA_TOPIC = 'S1',
  PARTITIONS = 12,
  REPLICAS = 1,
  VALUE_FORMAT = 'JSON'
);

CREATE STREAM S2 (
  NAME STRING KEY,
  COUNTRY STRING
)
WITH (
  KAFKA_TOPIC = 'S2',
  PARTITIONS = 12,
  REPLICAS = 1,
  VALUE_FORMAT = 'JSON'
);

CREATE STREAM OUTPUT
WITH (KAFKA_TOPIC = 'OP')
AS
  SELECT
    S1.NAME AS NAME,
    S1.AGE AS AGE,
    S2.COUNTRY AS COUNTRY
  FROM S1 JOIN S2
    WITHIN 10 SECONDS ON S1.NAME = S2.NAME;

CREATE STREAM S3 (NAME STRING KEY, AGE BIGINT, COUNTRY STRING)
WITH (KAFKA_TOPIC = 'S3', PARTITIONS = 1, REPLICAS = 1, VALUE_FORMAT = 'JSON');

INSERT INTO OUTPUT
SELECT * FROM S3;