global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 30s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'ccloudexporter'
    scrape_interval: 60s
    scrape_timeout: 30s
    honor_timestamps: true
    static_configs:
      - targets: ['ccloud_exporter:2112']
  - job_name: 'kafka-streams'
    static_configs:
      - targets:
        - 'stateless-in-out-1:8080'
        - 'stateless-in-out-2:8080'
        - 'stateless-in-out-3:8080'
        - 'stateless-in-out-4:8080'
        - 'stateless-in-out-5:8080'
        - 'stateless-in-out-6:8080'
      - labels:
          app: 'stateless-in-out'